---
title: "EDA"
output: html_document
---

```{r}
#load libraries
library(tidyverse)
library(lubridate)
library(leaflet)
library(webshot2)
library(mapview)
```

```{r}
#load crash data 
setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/data/external")
Crash <- read.csv("CleanedCrashData.csv")
#load cleaned weather dataset
setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/data/processed")
Weather <- read.csv("CleanedWeatherData.csv")
```
```{r}
#Show head structure and summary of prcp variable for the weather dataset
head(Weather)
str(Weather)
summary(Weather$totalprcp)
```
```{r}
#graph totalprcp variable and save to eda/images in github
p1 <- ggplot(Weather,aes(totalprcp))+
  geom_histogram(fill = "blue", color = "blue3")+
  labs(title = "Percipitation",
    x = "Percipitation (In)", caption = "data from NOAA available https://www.ncei.noaa.gov/cdo-web/"
  ) +
  theme_minimal()+
  theme(axis.title.y = element_blank())
p1
setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/eda/images")
ggsave("totalprcp_histogram.png", plot = p1, width = 8, height = 6)

#now do the same but log scale total prcp to reduce the effect of outliers on graph
p2 <- ggplot(Weather,aes(log10(totalprcp)))+
  geom_histogram(fill = "blue", color = "blue3")+
  labs(title = "Percipitation (log) distribution",
    x = "Percipitiation (log(In))", caption = "data from NOAA available https://www.ncei.noaa.gov/cdo-web/"
  ) +
  theme_minimal()+
  theme(axis.title.y = element_blank())
p2
setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/eda/images")
ggsave("totalprcp_histogram_logscaled.png", plot = p2, width = 8, height = 6)
```

```{r}
#Show head structure of Crash Data
head(Crash)
str(Crash)
```
```{r}
#make new dataset of number of crashes per day
Crash_Count <- Crash |>
  count(date, name = "numcrash") 

#createline graph to analyse crash data over time
p3 <- ggplot(Crash_Count)+
  geom_line(aes(x = as.numeric(as.Date(date)), y = numcrash))+
  scale_x_continuous(labels = function(x) format(as.Date(x, origin = "1970-01-01"), "%Y-%m-%d")) +
  labs(
    title = "Crashes Vs Time",
    x = "Time",
    y = "Crashes"
  ) 

p3
setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/eda/images")
ggsave("crash_vs_time_line.png", plot = p3, width = 40, height = 6)

```

```{r}
#filter only one day to make it easier on the computer
day_weather <- Weather |> filter(date == as.Date("2025-01-01"))
#create map of location of weather stations
m <- leaflet()|>
  setView(lng = -77.20, lat = 39.14, zoom =10) |>
  addTiles()|>
  addCircles(data = day_weather, color = "Black", opacity = 1)
#save to github
  setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/eda/images")
  mapview::mapshot2(m, "temp.html")
  webshot2::webshot("temp.html", file = "weather_stations.png")
  
```
```{r}
m2 <- leaflet()|>
  setView(lng = -77.20, lat = 39.14, zoom =10) |>
  addTiles()|>
  addCircles(data = Crash, color = "Black", opacity = 0.1)
m2
  setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/eda/images")
  mapview::mapshot2(m2, "temp.html")
  webshot2::webshot("temp.html", file = "crashes.png")
```

