---
title: "Analysis"
output: html_document
---

```{r}
library(tidyverse)
library(gstat)
library(sp)
library(raster)
library(leaflet)
library(tigris)
library(mapview)
library(glue)
```

```{r}
#upload crash data then create new dataset which is just the number of crashes for a given day
setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/data/external")
Crash <- read.csv("CleanedCrashData.csv")
Crash_Count <- Crash |>
  count(date, name = "count") 

#upload weather data then create new dataset of daily precipitation averages
setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/data/processed")
Weather <- read.csv("CleanedWeatherData.csv")
Avg_Prcp <- Weather |>
  group_by(date) |>
  summarise(avg_prcp = mean(totalprcp)) |> 
  ungroup()   

#merge two new datasets based on date.
Crash_Prcp <- merge(Crash_Count, Avg_Prcp, by = "date")
```
```{r}
# graph average precipitation vs number of crashes
p1 <- ggplot(Crash_Prcp, aes(x = count,y = log10(avg_prcp)))+
  geom_point()+
  geom_smooth(method = "lm", se = TRUE, color = "red", linetype = "solid")+
  labs(
    title = "Number of Crashes Vs Log of Average Percipitation",
    x = "Number of Crashes",
    y = "Log Average Percipitiation"
  ) +
  theme_minimal()
p1
#save graph to github
setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/analysis/images")
ggsave("AvgPrcp_vs_NumCrashes.png", plot = p1, width = 8, height = 6)
```
```{r}
#Conduct correlation test
result <- cor.test(Crash_Prcp$count, Crash_Prcp$avg_prcp)

print(result)
```

```{r}
MapWeather <- function(weather_data,crash_data, day){
  day_weather <- weather_data |> filter(date == day)
  coordinates(day_weather)<-~longitude+latitude
  
  day_crash <- crash_data |> filter(date==day)
  
  options(tigris_class = "sf")
  montgomery <- counties(state = "24", cb = TRUE, year = 2022) |>
  filter(NAME == "Montgomery")
  
  grd <- expand.grid(
  x = seq(-77.9, -76.9, by = 0.001),
  y = seq(38.8, 39.5, by = 0.001)  
  )
  coordinates(grd) <- ~x + y
  gridded(grd) <- TRUE
  
  variogram_model <- variogram(totalprcp ~ 1, data = day_weather)
  fitted_model <- fit.variogram(variogram_model, model = vgm("Sph"))
  
  
  kriging_result <- krige(totalprcp ~ 1, locations = day_weather, newdata = grd, model = fitted_model)

  kriging_raster <- raster(kriging_result)
  
  crs(kriging_raster) <- "EPSG:4326"
  
  raster_mont <- mask(kriging_raster, montgomery)
  
  
  pal <- colorNumeric(
  palette = "Blues",  
  domain = values(raster_mont),    
  na.color = "transparent"
)
  leaflet() |>
  setView(lng = -77.20, lat = 39.14, zoom =10) |>
  addTiles() |>
  addRasterImage(raster_mont, opacity = 0.85, project = TRUE, colors = pal)|>
  addCircles(data = day_crash, color = "Black")
  
  
  l1 <- leaflet() |>
  setView(lng = -77.20, lat = 39.14, zoom =10) |>
  addTiles() |>
  addRasterImage(raster_mont, opacity = 0.85, project = TRUE, colors = pal)|>
  addCircles(data = day_crash, color = "Black")
  
  setwd("~/Data205/Data-205-Capstone-Paul-Hanscom/analysis/images")
  mapshot(l1, file =glue("{day}.png"))
  
}
```
}
```

```{r}
MapWeather(Weather_Cleaned,Crash, "2025-01-01")

```

